export const initialFiat = [
    {value: 'RUB', selected: true},
    {value: 'KZT', selected: false},
    {value: 'USD', selected: false},
    {value: 'EUR', selected: false}
];
export const initialCrypto = [
    {value: 'BTC', selected: true},
    {value: 'USDT', selected: false},
    {value: 'RUB', selected: false},
    {value: 'ETH', selected: false},
    {value: 'BUSD', selected: false},
    {value: 'BNB', selected: false}
];

export const aggreg1 = ['Первая биржа', 'Покупаем как'];
export const aggreg2 = ['Вторая биржа', 'Продаем как'];


export const exchangesBanksMap: { [key: string]: Array<string> } = {
    'Binance':[
        "Tinkoff",
        "RosBank",
        "Raiffeisenbank",
        "QIWI",
        "Юmoney",
        // "MTS-Bank",
        // "Post Bank",
        // "BinancePay (RUB)",
        // "Home Credit Bank (Russia)",
        "Ak Bars Bank",
        "Payeer",
        // "Uralsib Bank",
        // "Renaissance Credit Bank",
        // "BCS Bank",
        // "Mobile top-up",
        // "Advcash",
        // "Bank Saint-Petersburg",
        // "OTP",
        // "Russian Standard Bank",
        // "UniCredit",
        "Bank Transfer",
        // "A-Bank",
        // "Credit Europe Bank (Russia)",
        // "Citibank (Russia)",
        // "Raiffeisen Bank Aval",
        // "Transfers with specific bank",
        // "Cash in Person",
        "Alfa-bank",
        // "Cash Deposit to Bank",
        // "Privat Bank (Universal Card)",
        "SBP - Fast Bank Transfer",
        "Sberbank",
        "VTB Bank"
    ],
    'Bitpapa': [
        "Bank transfers",
        "Sberbank",
        "Tinkoff",
        "QIWI",
        "Alfabank",
        "card2card",
        // "SBP",
        "Raiffeisen",
        "Yandex Money Yoomoney",
        // "VTB",
        // "Otkrytie",
        "Gazprombank",
        // "ERIP",
        // "Monobank",
        // "Mobile Recharge",
        // "Privatbank",
        // "Pochta bank",
        // "MTS bank",
        "Tinkoff QR",
        // "Other",
        // "CASH",
        "Paypal",
        // "Sovcombank",
        // "Homecredit",
        // "Uralsib",
        // "Promsvyaz bank",
        // "Rosselkhozbank",
        "Alfabank Cash-In",
        // "PUMB",
        // "Revolut",
        "Tinkoff Cash-In",
        "RNKB-bank",
        "USDT Tether",
        "Kaspi Bank",
        "Payeer RUB",
        "AK bars",
        // "A-bank",
        "Webmoney",
        // "Russkiy standart",
        // "Sankt-Peterburg bank",
        "Halyk Bank",
        // "Oschadbank",
        // "BTC Bitcoin",
        // "Payeer USD",
        // "Chipper Cash",
        // "Rosbank",
        // "SEPA",
        // "Perfect money",
        // "GlobalMoney",
        // "Paysend",
        "Binance",
        // "ForteBank",
        // "TsentrCredit bank",
        // "Avangard bank",
        // "MKB bank",
        // "MTBank",
        // "GTBank",
        // "Advanced cash USD",
        // "Aziatsko-Tikhookenaskiy bank",
        // "Rossiya bank",
        // "TransferWise",
        // "Advanced cash RUB",
        // "BKS bank",
        // "PriorBank",
        // "Binbank",
        // "Skrill",
        // "Western Union",
        // "PaySera",
        // "Payeer EUR",
        // "Cash By Mail",
        // "Amazon Gift Card",
        // "Credit Ural bank",
        // "Kukuruza",
        // "Zolotaya Korona",
        // "Steam Gift Card",
        // "Credit Evropa bank",
        // "MoneyGram",
        // "iTunes Gift Card",
        // "ApplePay",
        // "Zelle",
        // "UnionPay",
        // "Ria Money Transfer",
        // "Razer Gold Gift Card",
        // "Payoneer",
        // "MTN Mobile Money",
        // "Idram",
        // "Check",
        // "Airtel Money",
        // "Walmart Visa Gift Card",
        // "Visa Gift Card",
        // "Unistream",
        // "Neteller",
        // "ETH Ethereum",
        // "Contact",
        // "Cardless Cash",
        // "SWIFT",
        // "QAZKOM",
        // "Paritet Bank",
        // "Technobank",
        // "Xpress Money",
        // "Worldremit",
        // "Walmart Gift Card",
        // "Transfast",
        // "Paxum",
        // "OneVanilla VISA/MasterCard Gift Card",
        // "Localbitcoins",
        // "GCash",
        // "Epay",
        // "eBay Gift Card",
        // "EasyPay",
        // "OKX",
        // "Bancolombia Cash Deposit",
        // "American Express Gift Card",
        // "Airbnb Gift Card",
        // "Advanced cash EUR",
        // "MBANK",
        // "TK Bank",
        // "N26",
        // "Statusbank",
        // "ATFBank",
        // "Bank Kyrgyzstan",
        // "Xoom",
        // "Xbox Gift Card",
        // "WeChat",
        // "Vodafone Cash Deposit",
        // "Uphold",
        // "Uber Gift Card",
        // "Uber Eats",
        // "Target Visa Gift Card",
        // "Swish",
        // "Starbucks Gift Card",
        // "Spotify Gift Card",
        // "SolidTrust Pay",
        // "Sendwave",
        // "Postal Money Order",
        // "PokerStars Gift Card",
        // "Paysafecard",
        // "Paymer",
        // "Paxful",
        // "OXXO",
        // "Offgamers.com Gift Card",
        // "NixMoney",
        // "Nintendo Gift Card",
        // "Newegg Gift Card",
        // "Netflix Gift Card",
        // "Neosurf",
        // "M-PESA",
        // "MasterCard Gift Card",
        // "Lyft Gift Card",
        // "Liqpay",
        // "innopay",
        // "Google Play Gift Card",
        // "GameStop Gift Card",
        // "G2A Gift Card",
        // "EzRemit",
        // "EXMO Code",
        // "Epese",
        // "Epayments",
        // "E-kzt",
        // "Capitalist",
        // "Booking.com Gift Card",
        // "Bonus Bitpapa",
        // "Bitzlato Check",
        // "Bitrefill Balance Card",
        // "Bitcoin ATM",
        // "Apple Store Gift Card",
        // "Apple Gift Card",
        // "AMC Theaters Gift Card",
        // "American Apparel Gift Card",
        // "Alipay",
        // "Advanced cash UAH",
        "Adidas Gift Card"
    ]
}

export const initialBanks: Array<{value: string, selected: boolean}> = exchangesBanksMap.Binance.map(bank => ({value: bank, selected: false}))

// export const initialBanks = [
//     {value: 'Credit Europe Bank', selected: false},
//     {value: 'Payeer', selected: false},
//     {value: 'QIWI', selected: false},
//     {value: 'Raiffeisen Bank', selected: false},
//     {value: 'Raiffeisen Bank Aval', selected: false},
//     {value: 'Ак Барс Банк', selected: false},
//     {value: 'БКС Банк', selected: false},
//     {value: 'Сбербанк', selected: false},
// ];

export const initialAggregators: Array<{value: string, selected: boolean}> = [
    {value: 'Binance', selected: false},
    // {value: 'Garantex', selected: false},
    {value: 'Bitpapa', selected: false},
    // {value: 'Pexpay', selected: false},
    // {value: 'Bybit', selected: false},
    // {value: 'OKX', selected: false},
    // {value: 'Huobi', selected: false},
    // {value: 'LocalBitcoins', selected: false}
];
